### PR TITLE
Add support for PHP 7 scalar typehints

### PR DESCRIPTION
**Pull request by vysinsky**

### CODE REVIEW

**Comment by janmarek** [comment]
Can you please add tests?

**Comment by vysinsky** [comment]
Added. I don't know how to properly test scalar return types in `ClassGeneratorTest` is this enough?

**Comment by vysinsky** [comment]
Hi, could be this merged? :)

**Comment by f3l1x** [comment]
Hi. I'm new collaborator. I think we could merge. Let me first take some time to review it and a I will merge it later. Do you agree?

**Comment by vysinsky** [comment]
I do. Thank you.

**Comment by f3l1x** [comment]
It looks great, I will merge it tomorrow. Thank you.

**Comment by vysinsky** [comment]
Great to hear. Thank you.

**Comment by f3l1x** [comment]
@vysinsky Maybe one more thing. Can you please rebase it?

Cause Github's complaining:

> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by vysinsky** [comment]
I will do it asap (I did not see that on mobile, sorry).

**Comment by vysinsky** [comment]
done, sorry for delay

**Comment by f3l1x** [comment]
Rebased & merged, thank you.

**Pull request merged**
